### ISSUE TITLE
toHaveChildren throws error 'serializes to the same string'

### ISSUE THREAD

**Issue by fertavora** [webdriverio/expect-webdriverio#65]
Hi all!
I am checking out webdriverio 6 and I got an error using `toHaveChildren`
```
Expect $$(`div.card`) to have children
Expected: 9
Received: serializes to the same string
```
However when using `toBeElementsArrayOfSize` instead it works fine, according to the docs it is _Same as toHaveChildren_.
`expect(StoreHomePage.productCards).toBeElementsArrayOfSize({ eq: 9 });` works fine
`expect(StoreHomePage.productCards).toHaveChildren({ eq: 9 });` fails
`StoreHomePage.productCards` is `$$('div.card')`

Context:
`"@wdio/cli": "^6.1.5"`

node --version
v12.16.1

**Comment by mgrybyk** [comment]
@fertavora @vbyjsue there was a mistake in the doc.
`toBeElementsArrayOfSize` is used to check items in the elements array (`$$('ul>li')`).

While `toHaveChildren` is used to check children amount of the element (`$('ul')`).

Example
there is a list with 3 items
```
ul
   li
   li
   li
```
We pass element that is a parent of `li` items to `toHaveChildren` matcher:
* `expect($('li')).toHaveChildren(3)` or `expect($('li')).toHaveChildren({ eq: 3 })` - exact value
* `expect($('li')).toHaveChildren()` - there is at least one item in the list

While `toBeElementsArrayOfSize` expects an elements array:
* `expect($$('ui>li').toBeElementsArrayOfSize(3)` or `expect($$('ui>li').toBeElementsArrayOfSize({ eq: 3 })` - exact value

Thanks for submitting defects anyway. `toHaveChildren` doesn't work as expect and will be fixed with the PR.

**Comment by shiskr** [comment]
@mgrybyk 
Suppose there is a list with 3 different items

ul
   li
   div
   img
We pass element that is a parent of li items to toHaveChildren matcher:

expect($('ul')).toHaveChildren()
This should work, right??
Just confirming.

**Comment by mgrybyk** [comment]
Yes, as soon as ul has at least one child element of any tag type.

Let me know if you have any issues with it
