### ISSUE TITLE
Add better documentation how to create custom matchers

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/expect-webdriverio#835]
see https://github.com/webdriverio/expect-webdriverio/pull/797#issuecomment-1216434441

**Comment by paymand** [comment]
With the current released version, i.e. `3.4.0`, the only workaround is going to be what I mentioned in https://github.com/webdriverio/expect-webdriverio/pull/797#issuecomment-1216434441
For the next version `4.0.0`, I'm not sure since it's been rewritten to ESM (breaking change) and the code has changed quite a lot. I tried installing `expect-webdriverio@4.0.0-alpha.3` and converting our tests to ESM, but realized that it won't work since we'll need releases for all other packages with ESM support.

I can document my workaround for custom matchers, if you like me to, until we have the new versions out.

**Comment by christian-bromann** [comment]
> I can document my workaround for custom matchers, if you like me to, until we have the new versions out.

That would be great, thanks!
